"""Initial schema setup based on models and schema.sql

Revision ID: 8d548364498d
Revises: af0da1206605
Create Date: 2025-05-29 00:14:42.606228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d548364498d'
down_revision = 'af0da1206605'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drop_note', schema=None) as batch_op:
        batch_op.drop_index('idx_drop_note_modification_code')
        batch_op.drop_index('idx_drop_note_tags', postgresql_using='gin', postgresql_where="(visibility = 'public'::text)")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drop_note', schema=None) as batch_op:
        batch_op.create_index('idx_drop_note_tags', ['tags'], unique=False, postgresql_using='gin', postgresql_where="(visibility = 'public'::text)")
        batch_op.create_index('idx_drop_note_modification_code', ['modification_code'], unique=False)

    # ### end Alembic commands ###
