"""empty message

Revision ID: fda94c133ca4
Revises: 
Create Date: 2025-05-05 15:47:58.722962

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fda94c133ca4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drop_note',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('username', sa.TEXT(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.TEXT()), nullable=True),
    sa.Column('visibility', sa.TEXT(), nullable=False),
    sa.Column('modification_code', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('modification_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drop_note')
    # ### end Alembic commands ###
